new style snpcheck

diff --git a/pipeline/check_quality b/pipeline/check_quality
--- a/pipeline/check_quality
+++ b/pipeline/check_quality
@@ -1,7 +1,9 @@
 #!/bin/bash
 
 setpath=$1
-SNPCHECK_SCRIPT=/bin/true
+HEALTHCHECKLOGS_DIR=/data/common/dbs/healthchecklogs/
+SNPCHECK_VCFS_DIR=/data/common/dbs/snpcheck/32SNPtaq/samplevcfs/
+SNPCHECK_SCRIPT=snpcheck_compare_vcfs
 CHECKPIPELINE_SCRIPT=check_pipeline_output
 HEALTHTESTS_SCRIPT=do_healthcheck_qctests
 
@@ -22,6 +24,9 @@ function main() {
     echo '----- Health Tests -----'
     runHealthTests $setpath || ((failures++))
     
+    echo '----- verify s3 md5 -----'
+    runVerifyMd5 $setpath || ((failures++))
+    
     [[ $failures -gt 0 ]] && error "${failures} FAILURES IN ${setname}"
     echo 
     
@@ -29,7 +34,25 @@ function main() {
 
 function runSnpCheck() {
     local setpath=$1 && shift
-    if $SNPCHECK_SCRIPT -r ${setpath}
+    local setname=$( basename ${setpath} )
+
+    ## dirty: get unique ref sample id by parsing setname
+    local sampleid=$( echo $setname | cut -d"_" -f3 )
+
+    ## get snpcheck file in rundir
+    ## should be done using metadata json but does not contain barcode yet
+    local wgsvcf=$( find ${setpath} -name "*_32SNPtaq.vcf" | head -1 )
+    if [[ -z ${wgsvcf} ]]; then fail "[ERROR] No wgs snpcheck vcf found" && return 1; fi
+
+    ## get file to compare with
+    local arrvcf=$( find ${SNPCHECK_VCFS_DIR} -name "*${sampleid}*_OpenArrayCalls.vcf" | head -1 ) 
+    if [[ -z ${arrvcf} ]]; then fail "[ERROR] No array snpcheck vcf found" && return 1; fi
+
+    #echo "sampleid = ${sampleid}"
+    #echo "wgs vcf = ${wgsvcf}"
+    #echo "arr vcf = ${arrvcf}"
+
+    if $SNPCHECK_SCRIPT "$wgsvcf" "$arrvcf"
     then
         ok
         return 0
@@ -54,7 +77,7 @@ function runCheckPipelineOutput() {
 function runHealthTests() {
     local setpath=$1 && shift
     setname=$( basename $setpath )
-    hclogfile=${1}/logs/healthcheck.json
+    hclogfile=${HEALTHCHECKLOGS_DIR}/${setname}"_healthcheck"
     if $HEALTHTESTS_SCRIPT --healthcheck-log-file ${hclogfile}
     then
         ok
@@ -63,6 +86,39 @@ function runHealthTests() {
         fail "[ERROR] $?"
         return 1
     fi
+}
+
+function runVerifyMd5() {
+    local setpath=$1 && shift
+    verifyLogFile=${setpath}/logs/verify_s3_md5.log
+    
+    ## check if file exists
+    if [[ ! -f $verifyLogFile ]]; 
+    then
+        fail "[FAIL] No verify log file found ($verifyLogFile)"
+        return 1
+    fi
+    
+    ## check if file has content
+    if [[ $( cat ${verifyLogFile} | wc -l ) -eq 0 ]]; 
+    then 
+        fail "[FAIL] No lines in verifyLog ($verifyLogFile)"
+        return 1
+    fi
+           
+    ## check if all md5sums in file occur twice (for local and remote)
+    cat ${verifyLogFile} | grep -Po "(^[^\s]+)" | while read checksum; 
+    do 
+        foundCount=$( grep -c ${checksum} ${verifyLogFile}; )
+        if [[ ! ${foundCount} -eq 2 ]]; then
+            fail "[FAIL] ${checksum} not found twice in ${verifyLogFile}"
+            fail "  check manually: grep ${checksum} ${verifyLogFile}"
+            return 1
+        fi
+    done
+    
+    ok
+    return 0
 }
 
 function log() {
