disable runSnpCheck and runVerifyMd5

diff --git a/pipeline/perform_pipeline_qc b/pipeline/perform_pipeline_qc
--- a/pipeline/perform_pipeline_qc
+++ b/pipeline/perform_pipeline_qc
@@ -18,14 +18,14 @@ function main() {
     echo '----- Technical Check -----'
     runCheckPipelineOutput $setpath || ((failures++))
     
-    echo '----- SNP Check -----'
-    runSnpCheck $setpath || ((failures++))
+    ## echo '----- SNP Check -----'
+    ## runSnpCheck $setpath || ((failures++))
     
     echo '----- Health Tests -----'
     runHealthTests $setpath || ((failures++))
     
-    echo '----- verify s3 md5 -----'
-    runVerifyMd5 $setpath || ((failures++))
+    ## echo '----- verify s3 md5 -----'
+    ## runVerifyMd5 $setpath || ((failures++))
     
     [[ $failures -gt 0 ]] && error "${failures} FAILURES IN ${setname}"
     echo 
